version: "3.5"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - "8080:80"
    links:
      - fpm
    volumes:
      - ./:/var/www/phpunix
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    #entrypoint: sh /bin/run.sh
    volumes:
      - ./:/var/www/phpunix
      - ./scripts/phpEntry.sh:/bin/run.sh
    env_file:
      - '.env'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: phpunix
      MYSQL_ROOT_PASSWORD: 1111
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpunix_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

#Volumes
volumes:
  mysqldata:
    driver: local
